apiVersion: v1
kind: Service
metadata:
  name: order-and-payment-management
  labels:
    app: order-and-payment-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: order-and-payment-management