apiVersion: v1
kind: Service
metadata:
  name: delivery-and-order-status-management
  labels:
    app: delivery-and-order-status-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: delivery-and-order-status-management