apiVersion: v1
kind: Service
metadata:
  name: menu-and-restaurant-management
  labels:
    app: menu-and-restaurant-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: menu-and-restaurant-management