---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-and-payment-management
  labels:
    app: order-and-payment-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-and-payment-management
  template:
    metadata:
      labels:
        app: order-and-payment-management
    spec:
      containers:
        - name: order-and-payment-management
          image: username/order-and-payment-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-and-restaurant-management
  labels:
    app: menu-and-restaurant-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu-and-restaurant-management
  template:
    metadata:
      labels:
        app: menu-and-restaurant-management
    spec:
      containers:
        - name: menu-and-restaurant-management
          image: username/menu-and-restaurant-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-and-order-status-management
  labels:
    app: delivery-and-order-status-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-and-order-status-management
  template:
    metadata:
      labels:
        app: delivery-and-order-status-management
    spec:
      containers:
        - name: delivery-and-order-status-management
          image: username/delivery-and-order-status-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-management
  labels:
    app: system-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-management
  template:
    metadata:
      labels:
        app: system-management
    spec:
      containers:
        - name: system-management
          image: username/system-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: order-and-payment-management
  labels:
    app: order-and-payment-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: order-and-payment-management


---


apiVersion: v1
kind: Service
metadata:
  name: menu-and-restaurant-management
  labels:
    app: menu-and-restaurant-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: menu-and-restaurant-management


---


apiVersion: v1
kind: Service
metadata:
  name: delivery-and-order-status-management
  labels:
    app: delivery-and-order-status-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: delivery-and-order-status-management


---


apiVersion: v1
kind: Service
metadata:
  name: system-management
  labels:
    app: system-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: system-management

